"""Emit the main-table baseline rows from an aggregate JSON, or refuse (F15).

The main table was assembled by hand from whatever aggregation happened to be
open, so a number could reach the paper without the matrix that produced it ever
having been admissible. This generator closes that path:

  * the ONLY input is an aggregate JSON emitted by
    `aggregate_baseline_p0_matrix.py`, so every cell carries its manifest path,
    its implementation fingerprint and its own eligibility flag;
  * `--require-paper-eligible` (the default) refuses to write anything unless
    `paper_table_admission.eligible` is true, and prints the reason codes. A
    diagnostic-only matrix -- legacy cache provenance, missing seeds, blocked
    implementation drift -- produces NO TeX at all rather than TeX nobody
    notices is provisional;
  * the mean comes from `mean_map_at_R_post`, which the aggregator leaves null
    for a diagnostic-only cell. `diagnostic_mean_map_at_R_post` is never read
    here, so a diagnostic number cannot be typeset by accident.

Refusal is the point. Passing `--allow-diagnostic` stamps every emitted row and
the file header as diagnostic-only, which is meant to be visible in the diff.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Mapping, Sequence

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from dna_utils.bit_slice import resolve_bit_slice  # noqa: E402
from dna_utils.flat_geometry import resolve_flat_geometry  # noqa: E402

#: Row order in the paper. Anything absent from the aggregate prints as `-`.
ROW_ORDER = (
    "cibhash", "cimon", "mls3rduh", "greedyhash", "bihalf",
    "sdc-paper", "oh", "hhch", "crovca",
)
DISPLAY = {
    "cibhash": "CIBHash", "cimon": "CIMON", "mls3rduh": "MLS3RDUH",
    "greedyhash": "GreedyHash", "bihalf": "Bi-Half", "sdc-paper": "SDC",
    "oh": "OH", "hhch": "HHCH", "crovca": "CroVCA",
    "crh-supervised": "CRH (supervised)",
}
COLUMN_ORDER = ("Flickr25k", "MSCOCO", "NUSWIDE", "CIFAR10")
COLUMN_LABEL = {
    "Flickr25k": "Flickr25K", "MSCOCO": "MS-COCO",
    "NUSWIDE": "NUS-WIDE", "CIFAR10": "CIFAR-10",
}


class NotPaperEligible(RuntimeError):
    """The aggregate says its own numbers may not enter the paper table."""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def admission_failure_reasons(payload: Mapping[str, object]) -> list[str]:
    """Empty exactly when the aggregate admits itself to the paper table."""
    admission = payload.get("paper_table_admission")
    if not isinstance(admission, Mapping):
        return ["aggregate has no paper_table_admission block"]
    if admission.get("eligible") is True:
        return []
    raw = admission.get("reason_codes")
    codes = [str(code) for code in raw] if isinstance(raw, (list, tuple)) else []
    return codes or ["paper_table_admission.eligible is false"]


def _cell(entry: Mapping[str, object], *, allow_diagnostic: bool) -> str:
    mean = entry.get("mean_map_at_R_post")
    std = entry.get("sample_std_map_at_R_post")
    if mean is None and allow_diagnostic:
        mean = entry.get("diagnostic_mean_map_at_R_post")
        std = entry.get("diagnostic_sample_std_map_at_R_post")
    if mean is None:
        return "-"
    if std is None:
        return f"{float(mean):.4f}"
    return f"{float(mean):.4f} \\pm {float(std):.4f}"


def render_tex(payload: Mapping[str, object], *, source: Path,
               allow_diagnostic: bool = False) -> str:
    """The baseline block of the main table, plus its provenance header."""
    reasons = admission_failure_reasons(payload)
    if reasons and not allow_diagnostic:
        raise NotPaperEligible("; ".join(reasons))

    protocol = payload.get("protocol")
    protocol = protocol if isinstance(protocol, Mapping) else {}
    raw_slice = protocol.get("requested_bit_slice")
    bits = resolve_bit_slice(
        raw_slice if isinstance(raw_slice, (list, tuple)) else None)
    seeds = protocol.get("train_seeds")
    seeds = list(seeds) if isinstance(seeds, (list, tuple)) else []

    aggregates = payload.get("aggregates")
    aggregates = aggregates if isinstance(aggregates, list) else []
    by_cell: dict[tuple[int, str, str], Mapping[str, object]] = {}
    for entry in aggregates:
        if not isinstance(entry, Mapping):
            continue
        try:
            key = (int(entry["bit"]), str(entry["variant"]),
                   str(entry["dataset"]))
        except (KeyError, TypeError, ValueError):
            continue
        by_cell[key] = entry

    lines: list[str] = [
        "% GENERATED by scripts/build_maintable_from_aggregate.py -- do not edit.",
        f"% source: {source}",
        f"% source_sha256: {_sha256(source)}",
        f"% train_seeds: {seeds}",
        f"% generated_from_field: mean_map_at_R_post"
        f"{' (DIAGNOSTIC fallback allowed)' if allow_diagnostic else ''}",
    ]
    if reasons:
        lines.append("% DIAGNOSTIC-ONLY, NOT PAPER-ELIGIBLE: " + "; ".join(reasons))

    for bit in bits:
        geom = resolve_flat_geometry(bit)
        lines += [
            "",
            f"% ---- {bit} bit / {geom.total_bases} bases "
            f"({geom.num_codebooks}x{geom.bases_per_codebook}) ----",
        ]
        for variant in ROW_ORDER:
            cells = [
                _cell(by_cell[(bit, variant, dataset)],
                      allow_diagnostic=allow_diagnostic)
                if (bit, variant, dataset) in by_cell else "-"
                for dataset in COLUMN_ORDER
            ]
            label = DISPLAY.get(variant, variant)
            if reasons:
                label += r"$^{\dagger}$"
            lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Emit main-table baseline rows from an aggregate JSON.")
    parser.add_argument("aggregate", help="JSON from aggregate_baseline_p0_matrix.py")
    parser.add_argument("--out", default=None, help="TeX path; stdout if omitted.")
    parser.add_argument(
        "--require-paper-eligible", action=argparse.BooleanOptionalAction,
        default=True,
        help=("Refuse to emit anything unless the aggregate admits itself to "
              "the paper table (default true)."))
    parser.add_argument(
        "--allow-diagnostic", action="store_true",
        help=("Emit diagnostic-only numbers, stamping the header and every row "
              "with a dagger. Implies --no-require-paper-eligible."))
    args = parser.parse_args(argv)

    source = Path(args.aggregate).resolve()
    payload = json.loads(source.read_text(encoding="utf-8"))
    allow_diagnostic = bool(args.allow_diagnostic)
    if args.require_paper_eligible and not allow_diagnostic:
        reasons = admission_failure_reasons(payload)
        if reasons:
            print("REFUSED: the aggregate is not paper-table eligible.",
                  file=sys.stderr)
            for reason in reasons:
                print(f"  - {reason}", file=sys.stderr)
            print("No TeX was written. Re-run the matrix, or pass "
                  "--allow-diagnostic to emit dagger-stamped rows.",
                  file=sys.stderr)
            return 3

    tex = render_tex(payload, source=source, allow_diagnostic=allow_diagnostic)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(tex, encoding="utf-8")
        print(f"wrote {out}")
    else:
        print(tex, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
