#!/usr/bin/env python
"""TODO2 (§4.6 bio-projection effect) for the anchor model, from the admitted stage-T result set.

Every value comes from the two evaluation JSONs each admitted T record binds by digest, after
scripts/anchor_t_consumer.admit() has verified the whole chain (proposal v2). Formatting of stored values
only: no extraction, retrieval, projection or evaluation runs. Mean +/- sample sd over seeds {42,43,44}.

Usage: make_anchor_bioproj_table.py --inputs <consumer input manifest> --name <new bundle name>
       [--out-root /home/yschoi/gdna_anchor_downstream]
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))
from scripts import anchor_t_consumer as C  # noqa: E402

LABELS = (("CIFAR-10", "cifar10"), ("Flickr25K", "flickr25k"), ("NUS-WIDE", "nuswide"), ("MS-COCO", "mscoco"))
FIELDS = ("pre_map_at_R", "post_map_at_R", "delta_map_at_R", "mean_db_edits", "valid_pre", "valid_post",
          "unique_pre", "unique_post")


def derive(auth: C.Authority, inputs_path, reader: C.Reader) -> dict:
    admitted = C.admit(auth, inputs_path, reader)
    rows = {}
    for label, ds in LABELS:
        per_seed = {}
        for seed in C.SEEDS:
            x = C.cell_inputs(auth, reader, admitted["cells"][(ds, seed)])
            raw, bio = x["raw"], x["bio"]
            st = bio["bio_stats"]
            per_seed[seed] = {"pre_map_at_R": raw["mAP_at_R"], "post_map_at_R": bio["mAP_at_R"],
                              "delta_map_at_R": bio["mAP_at_R"] - raw["mAP_at_R"],
                              "mean_db_edits": st["db_mean_edit_distance"], "valid_pre": st["db_pre_compliance"],
                              "valid_post": st["db_post_compliance"], "unique_pre": raw["unique_code_ratio"],
                              "unique_post": bio["unique_code_ratio"], "R": raw["mAP_R_cutoff"],
                              "n_db": x["db_rows"], "origin": admitted["cells"][(ds, seed)]["origin"]}
        row = {"per_seed": {str(s): v for s, v in per_seed.items()}}
        for field in FIELDS:
            values = [per_seed[s][field] for s in C.SEEDS]
            row[field] = {"mean": statistics.fmean(values), "sample_sd": statistics.stdev(values),
                          "by_seed": {str(s): v for s, v in zip(C.SEEDS, values)}}
        rows[label] = row
    return {"rows": rows, "settlement": admitted["settlement"], "inputs_sha256": admitted["inputs_sha256"],
            "receipt_sha256": admitted["receipt_sha256"]}


def _f(x: float, digits: int = 4) -> str:
    return f"{x:.{digits}f}".lstrip("0") if abs(x) < 1 else f"{x:.{digits}f}"


def to_tex(d: dict) -> str:
    out = ["% Generated by scripts/make_anchor_bioproj_table.py -- do not hand-edit.",
           f"%   anchor model stage T; consumer inputs {d['inputs_sha256'][:12]}; seeds 42/43/44; 15 bases.",
           "% Formatting of stored values; not an independent numerical verification or paper acceptance.",
           "\\begin{tabular}{lcccccc}", "\\toprule",
           "Dataset & pre mAP@R & post mAP@R & paired $\\Delta$ & mean DB edits & DB valid pre & "
           "DB DNA-unique pre $\\rightarrow$ post \\\\", "\\midrule"]
    for label, _ in LABELS:
        r = d["rows"][label]
        m, s = (lambda k: r[k]["mean"]), (lambda k: r[k]["sample_sd"])
        out.append(f"{label} & ${_f(m('pre_map_at_R'))} \\pm {_f(s('pre_map_at_R'))}$ & "
                   f"${_f(m('post_map_at_R'))} \\pm {_f(s('post_map_at_R'))}$ & "
                   f"${m('delta_map_at_R'):+.4f} \\pm {_f(s('delta_map_at_R'))}$ & "
                   f"${m('mean_db_edits'):.3f} \\pm {s('mean_db_edits'):.3f}$ & "
                   f"${100 * m('valid_pre'):.1f} \\pm {100 * s('valid_pre'):.1f}\\%$ & "
                   f"${_f(m('unique_pre'))} \\pm {_f(s('unique_pre'))} \\rightarrow "
                   f"{_f(m('unique_post'))} \\pm {_f(s('unique_post'))}$ \\\\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(out)


def main(argv=None, *, authority: C.Authority | None = None, before_recheck=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--inputs", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out-root", default=C.DEFAULT_OUT_ROOT)
    args = parser.parse_args(argv)
    auth = authority or C.Authority()
    reader = C.Reader()
    try:
        d = derive(auth, args.inputs, reader)
        files = {"anchor_bioproj_15base_table.tex": to_tex(d),
                 "anchor_bioproj_15base_table.json": json.dumps(d, indent=1, sort_keys=True) + "\n"}
        dest = C.publish(args.out_root, "todo2_bioproj", args.name, files,
                         {"table": "TODO2 bio-projection", "source": C.source_identity(),
                          "generator_sha256": C.sha256(Path(__file__).resolve().read_bytes()),
                          "inputs_sha256": d["inputs_sha256"], "receipt_sha256": d["receipt_sha256"],
                          "settlement": d["settlement"]}, reader, before_recheck=before_recheck)
    except C.Refused as error:
        print(f"REFUSED: {error}", file=sys.stderr)
        return 2
    print(f"published {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
