#!/usr/bin/env python
"""TODO8 (§4.10.1 codebook NMI) for the anchor model, from the admitted stage-T result set.

Per cell, the mean over the ten unordered slot pairs of the pinned full-DB pairwise_nmi.json, after
scripts/anchor_t_consumer.admit() has verified the whole chain and cell_inputs() the binding and the
full-DB denominator (proposal v2). Formatting of stored values only: no extraction or NMI producer runs.
Then mean and sample sd over seeds {42,43,44}.

Usage: make_anchor_nmi_table.py --inputs <consumer input manifest> --name <new bundle name>
       [--out-root /home/yschoi/gdna_anchor_downstream]
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))
from scripts import anchor_t_consumer as C  # noqa: E402

LABELS = (("CIFAR-10", "cifar10"), ("Flickr25K", "flickr25k"), ("NUS-WIDE", "nuswide"), ("MS-COCO", "mscoco"))


def derive(auth: C.Authority, inputs_path, reader: C.Reader) -> dict:
    admitted = C.admit(auth, inputs_path, reader)
    rows = {}
    for label, ds in LABELS:
        per_seed = {}
        for seed in C.SEEDS:
            x = C.cell_inputs(auth, reader, admitted["cells"][(ds, seed)])
            per_seed[str(seed)] = {"mean_pairwise_nmi": x["mean_pair_nmi"], "min_pair_nmi": min(x["pairs"]),
                                   "max_pair_nmi": max(x["pairs"]), "db_rows": x["db_rows"],
                                   "observed_max_code_index_plus_one_per_slot": x["max_index_plus_one"],
                                   "distinct_codewords_per_slot": x["distinct_codewords"],
                                   "origin": admitted["cells"][(ds, seed)]["origin"]}
        means = [per_seed[str(s)]["mean_pairwise_nmi"] for s in C.SEEDS]
        mu = math.fsum(means) / len(means)
        sd = math.sqrt(math.fsum((v - mu) ** 2 for v in means) / (len(means) - 1))
        rows[label] = {"key": ds, "db_rows": per_seed["42"]["db_rows"], "per_seed": per_seed, "mean": mu,
                       "sample_sd": sd, "n_seeds": len(means)}
    return {"rows": rows, "settlement": admitted["settlement"], "inputs_sha256": admitted["inputs_sha256"],
            "receipt_sha256": admitted["receipt_sha256"]}


def to_tex(d: dict) -> str:
    out = ["% Generated by scripts/make_anchor_nmi_table.py -- do not hand-edit.",
           f"%   anchor model stage T; consumer inputs {d['inputs_sha256'][:12]}; stored pairwise_nmi.json files.",
           "% Formatting of stored values; not an independent numerical verification or paper acceptance.",
           "\\begin{tabular}{lrcccc}", "\\toprule",
           "Dataset & DB rows & seed 42 & seed 43 & seed 44 & mean $\\pm$ sd \\\\", "\\midrule"]
    for label, _ in LABELS:
        r = d["rows"][label]
        ps = r["per_seed"]
        out.append(f"{label} & {r['db_rows']:,}".replace(",", "{,}") + " & "
                   + " & ".join(f"{ps[str(s)]['mean_pairwise_nmi']:.4f}" for s in C.SEEDS)
                   + f" & ${r['mean']:.4f} \\pm {r['sample_sd']:.4f}$ \\\\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(out)


def main(argv=None, *, authority: C.Authority | None = None, before_recheck=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--inputs", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out-root", default=C.DEFAULT_OUT_ROOT)
    args = parser.parse_args(argv)
    auth = authority or C.Authority()
    reader = C.Reader()
    try:
        d = derive(auth, args.inputs, reader)
        files = {"anchor_nmi_15base_table.tex": to_tex(d),
                 "anchor_nmi_15base_table.json": json.dumps(d, indent=1, sort_keys=True) + "\n"}
        dest = C.publish(args.out_root, "todo8_nmi", args.name, files,
                         {"table": "TODO8 codebook NMI", "source": C.source_identity(),
                          "generator_sha256": C.sha256(Path(__file__).resolve().read_bytes()),
                          "inputs_sha256": d["inputs_sha256"], "receipt_sha256": d["receipt_sha256"],
                          "settlement": d["settlement"]}, reader, before_recheck=before_recheck)
    except C.Refused as error:
        print(f"REFUSED: {error}", file=sys.stderr)
        return 2
    print(f"published {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
