RT, TE, L, S = ("scripts/anchor_refit_stage.py", "scripts/anchor_terminal_test.py",
                "scripts/phase3_selection_matrix.py", "scripts/anchor_confirm_supervisor.py")
TR = "tests/test_anchor_t_recovery.py"
NO_RAISE = "DID NOT RAISE"
REGEX = "Regex pattern did not match"
POSITIVE = "test_composed_an_approved_recovery_runs_one_cell_and_writes_the_lineage_receipt"

MUTANTS = [
    ("RY1 carried cells skip the output-contract check", RT,
     '        if cell_id in carried_cells:\n            assert_carried_outputs(run_dir)\n',
     '        if cell_id in carried_cells:\n            pass\n',
     [((TR, "test_composed_a_carried_run_directory_off_the_output_contract_refuses[missing]"), NO_RAISE),
      ((TR, "test_composed_a_carried_run_directory_off_the_output_contract_refuses[bit2]"), NO_RAISE)]),
    ("RY2 the carried output contract is not enforced", RT,
     '    if missing or (Path(run_dir) / BIT2_OUTPUT).exists():\n',
     '    if False:\n',
     [((TR, "test_composed_a_carried_run_directory_off_the_output_contract_refuses[missing]"), NO_RAISE),
      ((TR, "test_composed_a_carried_run_directory_off_the_output_contract_refuses[bit2]"), NO_RAISE)]),
    ("RY3 membership is not exact", RT,
     '    if recovery["cell_id"] in carried or set(carried) | {recovery["cell_id"]} != set(cells):\n',
     '    if False:\n',
     [((TR, "test_composed_membership_is_exactly_the_twelve_minus_the_recovered_cell[missing-carried]"), REGEX)]),
    ("RY4 the carried pins may name another cell tag", RT,
     '        if pins.get("tag") != cell["tag"]:\n',
     '        if False:\n',
     [((TR, "test_composed_membership_is_exactly_the_twelve_minus_the_recovered_cell[crossed-tag]"), NO_RAISE)]),
    ("RY5 a carried record, attempt and entry need not be one lineage", RT,
     '            raise CellRefused(f"{cell_id}: the carried record, attempt and entry are not one stopped-campaign "\n'
     '                              "lineage")\n',
     '            pass\n',
     [((TR, "test_composed_a_carried_record_off_the_stopped_lineage_refuses[record-request]"), NO_RAISE),
      ((TR, "test_composed_a_carried_entry_not_binding_its_attempt_refuses"), NO_RAISE)]),
    ("RY6 the recovered cell may already have a stage-T record", RT,
     '        raise CellRefused("the recovered cell has a stage-T record: it is not the interrupted cell")\n',
     '        pass\n',
     [((TR, "test_composed_the_recovered_cell_with_a_stage_t_record_refuses"), NO_RAISE)]),
    ("RY7 the recovered cell may have been attempted in another namespace", RT,
     '        raise CellRefused(f"the recovered cell was attempted in another namespace: {others}")\n',
     '        pass\n',
     [((TR, "test_composed_the_recovered_cell_attempted_in_another_namespace_refuses"), NO_RAISE)]),
    ("RY8 a stopped campaign may have a receipt", RT,
     '        raise CellRefused("the stopped campaign has a receipt: it is not a stopped campaign")\n',
     '        pass\n',
     [((TR, "test_composed_a_stopped_campaign_with_a_receipt_refuses"), NO_RAISE)]),
    ("RY9 the settlement need not be the clean budget stop", RT,
     '        raise CellRefused("the stopped run\'s settlement is not the audited clean budget stop")\n',
     '        pass\n',
     [((TR, "test_composed_the_settlement_must_be_the_audited_clean_budget_stop[unclean]"), NO_RAISE),
      ((TR, "test_composed_the_settlement_must_be_the_audited_clean_budget_stop[wall-stop]"), NO_RAISE),
      ((TR, "test_composed_the_settlement_must_be_the_audited_clean_budget_stop[charge-reset]"), NO_RAISE)]),
    ("RY10 the stopped run need not end the ledger", RT,
     '        raise CellRefused("the stopped run is not exactly one start, stop and final, ending the ledger")\n',
     '        pass\n',
     [((TR, "test_composed_the_settlement_must_be_the_audited_clean_budget_stop[line-after-final]"), NO_RAISE)]),
    ("RY11 the settlement lines need not be their pinned bytes", RT,
     '            raise CellRefused(f"the stopped run\'s {kind} line is not its pinned bytes")\n',
     '            pass\n',
     [((TR, "test_composed_a_settlement_line_off_its_pin_refuses"), NO_RAISE)]),
    ("RY12 the stopped snapshot need not be the r7 run request", RT,
     '        raise CellRefused("the stopped stage-T snapshot is not the pinned r7 run request")\n',
     '        pass\n',
     [((TR, "test_composed_the_stopped_snapshot_of_another_generation_refuses"), REGEX)]),
    ("RY13 the reservation need not bind its snapshot", RT,
     '        raise CellRefused("the stopped campaign\'s reservation does not bind its snapshot")\n',
     '        pass\n',
     [((TR, "test_composed_a_reservation_not_binding_its_snapshot_refuses"), NO_RAISE)]),
    ("RY14 the recorded stopped line need not be the ledger's", RT,
     '        raise CellRefused("the stopped campaign\'s stage-T approval is not the ledger\'s line")\n',
     '        pass\n',
     [((TR, "test_composed_the_recorded_stopped_line_must_be_the_ledger_s"), NO_RAISE)]),
    ("RY15 any r7 -> r8 transition is accepted", RT,
     '    if changed != sorted(RECOVERY_CHANGED_CLOSURE) or added != sorted(RECOVERY_ADDED_CLOSURE) or removed:\n',
     '    if False:\n',
     [((TR, "test_composed_any_other_transition_refuses[extra-change]"), NO_RAISE),
      ((TR, "test_composed_the_plan_refuses_a_transition_other_than_the_declared_one"), "assert 0 == 2")]),
    ("RY16 the recovery may execute under r7", RT,
     '    if manifest["sha256"] == R7_MANIFEST_SHA256:\n',
     '    if False:\n',
     [((TR, "test_composed_any_other_transition_refuses[same-generation]"), NO_RAISE)]),
    ("RY17 the boundary allowlist is not exact", RT,
     '    if changed != sorted(RECOVERY_CHANGED_SOURCES):\n',
     '    if False:\n',
     [((TR, "test_composed_a_changed_source_outside_the_allowlist_refuses"), NO_RAISE)]),
    ("RY18 an allowlisted source need not be its r7 and committed r8 bytes", RT,
     '                raise CellRefused(f"{rel}: not its r7 bytes at stage R and its committed r8 bytes now")\n',
     '                pass\n',
     [((TR, "test_composed_an_allowlisted_source_off_its_r7_or_r8_bytes_refuses"), NO_RAISE),
      ((TR, "test_composed_an_uncommitted_allowlisted_source_refuses"), NO_RAISE)]),
    ("RY19 the source authority outside the allowlist may change", RT,
     '            raise CellRefused(f"{rel}: its source authority changed between stage R and the recovery")\n',
     '            pass\n',
     [((TR, "test_composed_a_changed_source_authority_outside_the_allowlist_refuses"), NO_RAISE)]),
    ("RY20 the recovery claim is not exclusive", RT,
     '    try:\n        M._publish_json_exclusive(path, payload)\n    except CellRefused:\n'
     '        raise CellRefused(f"the interrupted lineage',
     '    try:\n        path.unlink(missing_ok=True)\n        M._publish_json_exclusive(path, payload)\n'
     '    except CellRefused:\n        raise CellRefused(f"the interrupted lineage',
     [((TR, "test_composed_the_lineage_is_recovered_once_even_after_a_failure[0]"), "assert 0 == 1")]),
    ("RY21 a request may name another claim root", RT,
     '    if request["claim_root"] != str(RECOVERY_CLAIM_ROOT):\n',
     '    if False:\n',
     [((TR, "test_composed_a_request_naming_another_claim_root_refuses"), NO_RAISE)]),
    ("RY22 the claim is not consumed before the attempt", RT,
     '    if before_attempt is not None:\n        before_attempt()\n',
     '    if False:\n        before_attempt()\n',
     [((TR, POSITIVE), "assert 1 == 0")]),
    ("RY23 the T entry does not verify the recovery authority", TE,
     '        if recovery:\n            # the recovery authority proven here',
     '        if False:\n            # the recovery authority proven here',
     [((TR, "test_composed_an_entry_without_the_claim_refuses_before_any_load"), "assert (0 == 2)"),
      ((TR, "test_composed_a_counterfeit_lineage_in_an_approved_request_refuses_the_entry"), "assert (0 == 2)")]),
    ("RY24 the entry accepts a request lineage off the pinned campaign", RT,
     '        raise CellRefused("the recovery request\'s lineage is not the pinned stopped campaign\'s")\n',
     '        pass\n',
     [((TR, "test_composed_a_counterfeit_lineage_in_an_approved_request_refuses_the_entry"), "assert (0 == 2)")]),
    ("RY25 the entry accepts a claim for another namespace or record root", RT,
     '    if {k: claim.get(k) for k in want} != want or attempt_path.name != want["attempt"]:\n',
     '    if False:\n',
     [((TR, "test_composed_a_claim_for_another_namespace_or_line_refuses_the_entry[other-namespace]"),
       "assert (0 == 2)"),
      ((TR, "test_composed_a_claim_for_another_namespace_or_line_refuses_the_entry[other-approval]"),
       "assert (0 == 2)")]),
    ("RY26 the entry accepts the stage-T form in the recovery mode", TE,
     '    need(recovery == (request.get("mode") == RT.RECOVERY_MODE)\n'
     '         and (not recovery or len(request.get("cells") or []) == 1),\n',
     '    need(True,\n',
     # audit 816: with the early mixed-form guard removed, this fixture's later request-approval check still
     # refuses (rc 2, no call); the mutant is detected through the changed diagnostic, NOT through an entry that
     # proceeds -- removing the guard alone does not admit the mixed request here
     [((TR, "test_composed_the_stage_t_form_with_the_recovery_mode_refuses"),
       "no standing stage-T approval for this request")]),
    ("RY27 the recovery entry expects a smoke horizon", TE,
     'if request.get("mode") in ("run", RT.RECOVERY_MODE) else',
     'if request.get("mode") in ("run",) else',
     [((TR, "test_composed_an_authorized_recovery_entry_runs_the_terminal_function_once"), "assert (2 == 0)")]),
    ("RY28 a stage-T-run line approves the recovery", RT,
     '    approval = M.audit_approval(args.anchor_approval_section, RECOVERY_SCOPE, manifest=manifest["sha256"],',
     '    approval = M.audit_approval(args.anchor_approval_section, "stage-T-run", manifest=manifest["sha256"],',
     [((TR, "test_composed_only_a_recovery_line_for_this_exact_request_approves[stage-T-run]"), "assert 0 == 2")]),
    ("RY29 carried payloads are not verified before the leases", RT,
     '    verify_carried_payloads(admitted)\n    M.recheck_generation(manifest, "after the recovery admission")\n',
     '    M.recheck_generation(manifest, "after the recovery admission")\n',
     [((TR, "test_composed_a_carried_payload_off_its_record_refuses_before_any_lease_or_claim"), "assert 1 == 2")]),
    ("RY30 the final closure does not re-verify the carried payloads", RT,
     '    verify_carried_payloads(admitted)\n    claim_path = recovery_claim_path(request["claim_key"])\n',
     '    claim_path = recovery_claim_path(request["claim_key"])\n',
     [((TR, "test_composed_drift_during_the_recovered_cell_publishes_no_combined_receipt[carried-binary]"),
       "assert 0 == 1"),
      ((TR, "test_composed_drift_during_the_recovered_cell_publishes_no_combined_receipt[carried-json]"),
       "assert 0 == 1")]),
    ("RY31 the final closure does not re-check the claim bytes", RT,
     '    if not claim_path.is_file() or M._sha(claim_path) != claim.get("sha256"):\n',
     '    if False:\n',
     [((TR, "test_composed_drift_during_the_recovered_cell_publishes_no_combined_receipt[claim]"), "assert 0 == 1")]),
    ("RY32 the final closure does not check the new cell's outputs", RT,
     '    assert_record_outputs(Path(cell["run_dir"]), record.get("completion") or {}, cell["cell_id"])\n'
     '    return {"carried"',
     '    return {"carried"',
     [((TR, "test_composed_a_new_record_off_its_outputs_publishes_no_receipt"), "assert 0 == 1")]),
    ("RY33 the final closure treats the executed cell as untouched", RT,
     '    holding = frozenset(carried) | (frozenset({recovery["cell_id"]}) if target_executed else frozenset())\n',
     '    holding = frozenset(carried)\n',
     [((TR, POSITIVE), "assert 1 == 0")]),
    ("RY34 the supervisor does not bind the parent ledger", S,
     '        if stage in REC_STAGES:\n            try:\n                parent = parent_settlement()',
     '        if False:\n            try:\n                parent = parent_settlement()',
     [((TR, "test_composed_a_changed_or_unsettled_parent_refuses_before_start[unsettled]"), "assert 0 == 2")]),
    ("RY35 the parent ledger need not be its pinned bytes", S,
     '    if digest != REC_PARENT_LEDGER_SHA256:\n',
     '    if False:\n',
     [((TR, "test_composed_a_changed_or_unsettled_parent_refuses_before_start[reformatted]"), "assert 0 == 2")]),
    ("RY36 the parent ledger need not end settled at its charge", S,
     '        raise Refused("the settled R/T ledger does not end settled at its pinned cumulative charge")\n',
     '        pass\n',
     [((TR, "test_composed_a_changed_or_unsettled_parent_refuses_before_start[unsettled]"), "assert 0 == 2"),
      ((TR, "test_composed_a_changed_or_unsettled_parent_refuses_before_start[other-charge]"), "assert 0 == 2")]),
    ("RY37 the recovery has no ledger group of its own", S,
     '              (REC_STAGES, REC_OPS_ROOT, REC_BUDGET_DEVICE_SECONDS))\n',
     '              )\n',
     [((TR, "test_composed_the_recovery_keeps_its_own_ledger_and_budget"), "assert (")]),
    ("RY38 the recovered cell's producers are counted as one", S,
     '"stage-T-run": 5, "stage-T-recovery": 5}',
     '"stage-T-run": 5}',
     [((TR, "test_composed_the_recovery_is_one_gpu_and_five_producers"), "KeyError")]),
    ("RY39 the recovery may use more than one GPU", RT,
     '    if len(gpus) != 1:\n        raise CellRefused(f"the recovery runs one cell on exactly one GPU',
     '    if False:\n        raise CellRefused(f"the recovery runs one cell on exactly one GPU',
     [((TR, "test_composed_the_request_is_one_gpu_and_a_new_namespace[two-gpus]"), "assert 0 == 2")]),
    ("RY40 the recovery may write the stopped namespace", RT,
     '    if str(args.namespace) == lineage["stopped"]["namespace"]:\n',
     '    if False:\n',
     [((TR, "test_composed_the_request_is_one_gpu_and_a_new_namespace[stopped-namespace]"), "assert 0 == 2")]),
    ("RY41 the recovery takes a stage-R receipt from the command", RT,
     '    if args.anchor_refit_receipt or args.anchor_refit_receipt_sha256:\n        raise CellRefused("the recovery takes',
     '    if False:\n        raise CellRefused("the recovery takes',
     [((TR, "test_composed_the_recovery_takes_no_receipt_smoke_or_cell_selection"), "assert 0 == 2")]),
    ("RY42 the recovery has no approval scope", L,
     '    "stage-T-recovery": ("manifest", "freeze", "request"),\n',
     '',
     [((TR, "test_structural_the_recovery_scope_binds_the_f_record"), "KeyError")]),
    ("RY43 the launcher does not dispatch the recovery to the stage", L,
     '    if args.anchor_confirm in ("refit", "test", "recover"):',
     '    if args.anchor_confirm in ("refit", "test"):',
     [((TR, "test_composed_the_plan_previews_one_cell_and_touches_nothing"), "assert 2 == 0")]),
    ("RY44 a manifest may omit the recovery contract", L,
     '    if manifest.get("recovery_contract") != {"path": ANCHOR_RECOVERY_CONTRACT_PATH,\n',
     '    if False and manifest.get("recovery_contract") != {"path": ANCHOR_RECOVERY_CONTRACT_PATH,\n',
     [((TR, "test_composed_a_manifest_without_the_recovery_contract_refuses"), NO_RAISE)]),
    ("RY45 the publication trusts the recorded attempt digest instead of the attempt file", RT,
     '    attempt, attempt_sha = _read_json(root / attempt_name, executed["attempt_sha256"],\n'
     '                                      "the recovered cell\'s attempt reservation")\n',
     '    attempt, attempt_sha = ({"schema": T_ATTEMPT_SCHEMA, "namespace": request["namespace"], '
     '"campaign_nonce": campaign_nonce, "request": request, "request_sha256": M._json_digest(request), '
     '"cell": cell, "approval": approval}, executed["attempt_sha256"])\n',
     [((TR, "test_composed_a_new_cell_chain_off_its_files_publishes_no_combined_receipt[new-attempt-changed]"),
       "assert 0 == 1"),
      ((TR, "test_composed_a_new_cell_chain_off_its_files_publishes_no_combined_receipt[new-attempt-missing]"),
       "assert 0 == 1")]),
    ("RY46 the new entry claim need not bind its attempt and cell", RT,
     '        raise CellRefused("the recovered cell\'s entry claim does not bind its attempt and cell")\n',
     '        pass\n',
     [((TR, "test_composed_a_new_cell_chain_off_its_files_publishes_no_combined_receipt[new-entry-mismatched]"),
       "assert 0 == 1")]),
    ("RY47 the new entry claim is not read", RT,
     '    entry, entry_sha = _read_json(root / entry_name, None, "the recovered cell\'s entry claim")\n',
     '    entry, entry_sha = ({"attempt": attempt_name, "attempt_sha256": attempt_sha, "cell_id": cell["cell_id"], '
     '"final_checkpoint_sha256": cell["final_checkpoint_sha256"], "config_pt_sha256": cell["config_pt_sha256"]}, '
     'None)\n',
     [((TR, "test_composed_a_new_cell_chain_off_its_files_publishes_no_combined_receipt[new-entry-missing]"),
       "assert 0 == 1")]),
]
